import { Monster, Quest } from "../types";

export const mockMonsters: Monster[] = [
  {
    id: "m1",
    name: "Bloop",
    personality: "Shy but curious",
    primaryEmotion: "worried",
    color: "#6B9BFF",
    isUnlocked: true,
    questIds: ["q1", "q3"],
    lottieAnimations: {
      happy: "",
      worried: "",
      angry: "",
      sad: "",
      relieved: "",
      proud: "",
    },
  },
  {
    id: "m2",
    name: "Grumble",
    personality: "Grumpy but kind-hearted",
    primaryEmotion: "angry",
    color: "#FF9F43",
    isUnlocked: false,
    questIds: ["q2"],
    lottieAnimations: {
      happy: "",
      worried: "",
      angry: "",
      sad: "",
      relieved: "",
      proud: "",
    },
  },
];

export const mockQuests: Quest[] = [
  {
    id: "q1",
    title: "The Missing Toy",
    monsterId: "m1",
    category: "mystery",
    difficulty: 1,
    isLocked: false,
    requiredXp: 0,
    strategy: "Ask for Help",
    strategyDescription:
      "When you can't find something, asking a friend makes it easier.",
    estimatedMinutes: 3,
    thumbnail: "🕵️‍♂️",
    startNodeId: "node1",
  },
  {
    id: "q2",
    title: "The Loud Noise",
    monsterId: "m2",
    category: "anger",
    difficulty: 2,
    isLocked: true,
    requiredXp: 50,
    strategy: "Pause & Breathe",
    strategyDescription: "Taking a deep breath helps calm our bodies.",
    estimatedMinutes: 4,
    thumbnail: "🔊",
    startNodeId: "node1",
  },
  {
    id: "q3",
    title: "Cloud Jumping",
    monsterId: "m1",
    category: "fear",
    difficulty: 1,
    isLocked: false,
    requiredXp: 0,
    strategy: "Be Brave",
    strategyDescription: "Trying new things can be scary but fun!",
    estimatedMinutes: 2,
    thumbnail: "☁️",
    startNodeId: "node1",
  },
  {
    id: "q4",
    title: "Shy at the Party",
    monsterId: "m1",
    category: "loneliness",
    difficulty: 3,
    isLocked: false,
    requiredXp: 10,
    strategy: "Say Hello",
    strategyDescription: "A simple wave can start a new friendship.",
    estimatedMinutes: 4,
    thumbnail: "🎉",
    startNodeId: "node1",
  },
];

export const monsterEmojis: Record<string, string> = {
  m1: "👾",
  m2: "😠",
};
